[repository]
name = "hypr-focus-shade"
authors = ["Praczet"]

[hypr-focus-shade]
description = "Focus-aware per-window shader effects for Hyprland"
authors = ["Praczet"]
output = "out/hypr-focus-shade.so"
build = [
    "make all -j",
]
